version: 0.2

phases:
  install:
    commands:
      - curl -o terraform.zip ${TERRAFORM_DOWNLOAD_URL} && unzip terraform.zip
      - mv terraform /usr/local/bin
  build:
    commands:
      - repo=$( ls | grep ${REPO_NAME})
      - cd $repo/tests
      - terraform init -input=false -no-color
      - terraform plan -detailed-exitcode -input=false -no-color | tee results.log
  post_build:
    commands:
      - cd
      - echo -e "{\"test\":\"terraform-plan\", \"build\":\""$CODEBUILD_BUILD_ID"\", \"status\":\""$CODEBUILD_BUILD_SUCCEEDING"\"}" > metadata.log
artifacts:
  files:
    - $repo/tests/results.log
    - metadata.log
  discard-paths: yes
