version: 0.2

phases:
  install:
    commands:
      - curl -o terraform.zip ${TERRAFORM_DOWNLOAD_URL} && unzip terraform.zip
      - mv terraform /usr/local/bin
      - apt-get -qq update
      - apt-get -qq install jq
  pre_build:
    commands:
      - export BUILD_URL="https://console.aws.amazon.com/codebuild/home?region=${AWS_REGION}#/builds/${CODEBUILD_BUILD_ID}/view/new"
      - export SHA=$( aws s3api get-object-tagging --bucket $S3_BUCKET --key $PR_NUMBER/repo.zip | jq '.TagSet[] | select(.Key=="latest_commit")' | jq -r '.Value' )
      - "jq -n -r --arg url \"$BUILD_URL\" '{ state: \"pending\", target_url: $url, description: \"Checks that terraform templates are formatted\", context: \"terraform-fmt\"}' > data.json"
      - "curl -d \"@data.json\" -H \"Content-Type: application/json\" -H \"Authorization: token ${GITHUB_PAC}\" -X POST \"${GITHUB_API_URL}/repos/${REPO_OWNER}/${REPO}/statuses/${SHA}\""
  build:
    commands:
      - repo=$( ls | grep ${REPO_NAME})
      - cd $repo
      - terraform fmt | tee results.log
      - if [ -s results.log ]; then echo "Unformatted templates detected" && exit 1; fi
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]; then export STATE="success"; else export STATE="failure"; fi
      - "jq -n -r --arg state \"${STATE}\" --arg url \"$BUILD_URL\" '{ state: $state, target_url: $url, description: \"Checks that terraform templates are formatted\", context: \"terraform-fmt\"}' > data.json"
      - "curl -d \"@data.json\" -H \"Content-Type: application/json\" -H \"Authorization: token ${GITHUB_PAC}\" -X POST $GITHUB_API_URL/repos/$REPO_OWNER/$REPO/statuses/$SHA"
      - echo "# terraform-fmt results for $SHA\nThe following files need to be formatted:\n" > results.txt && cat results.log >> results.txt
      - "jq -n -r --arg body \"$(cat results.txt)\" '{ body: $body }' > data.json"
      - "if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then curl -d \"@data.json\" -H \"Content-Type: application/json\" -H \"Authorization: token ${GITHUB_PAC}\" -X POST $GITHUB_API_URL/repos/$REPO_OWNER/$REPO/issues/$PR_NUMBER/comments ; fi"
